### PR TITLE
Fix error when file is uploaded as ZPublisher.HTTPRequest.FileUpload

### PR DESCRIPTION
**Pull request by Nachtalb**

### CODE REVIEW

**Comment by Nachtalb** [comment]
ATM there is a zcml conflict in the tests because the lastes released version of 4teamwork/ftw.file also adds this utility. This is removed and replaced with 4teamwork/ftw.uploadutility in this PR 4teamwork/ftw.file#99

**Comment by jone** [comment]
@Nachtalb we should also use the `ftw.uploadutility` here.

**Comment by jone** [comment]
@Nachtalb what is the state here?

**Comment by Nachtalb** [comment]
Rebased onto latest master.
@jone it's ready now. `ftw.file` has been released and thus the tests do not fail anymore.

**Pull request merged**
