### PR TITLE
Gridsystem could not get overriden.

### PR DESCRIPTION
**Pull request by bierik**
The gridsystem was too complicated and to specific. It couldnt get
overridden in other packages. So refactor the gridsystem with a variable
gutter.

### CODE REVIEW

**Comment by maethu** [comment]
please rebase

**Comment by maethu** [comment]
@bierik Please update/rebase this PR and explain the issue again :smile:

**Comment by maethu** [comment]
What ist the impact on actual sites?

**Comment by bierik** [comment]
@maethu updated

**Pull request merged**
